FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app

COPY . .
RUN npm install

RUN npm run build -w packages/shared
RUN npm run build -w apps/bot

EXPOSE 8080
CMD ["node", "apps/bot/dist/index.js"]
