[build]
nixpacksBuildCommand = "npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build"

[deploy]
startCommand = "sh start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
